#!/usr/bin/env python3
"""Fetch the shell's icons from Google's Material Symbols and write ../IconPaths.js.

Every name in names.txt is downloaded from github.com/google/material-design-icons
(symbols/web/<name>/materialsymbolsrounded) in the rice's style — Rounded,
filled, weight 600, grade 0 — twice: the drawing made for 20px (used up to
28px) and the one made for 40px (bigger). Icon.qml draws the path with the
theme's colour. Add a name to names.txt and run this again; nothing else
needs the network. Material Symbols are Apache-2.0 (Google).
"""
import json, os, re, sys, urllib.request
from concurrent.futures import ThreadPoolExecutor

HERE = os.path.dirname(os.path.abspath(__file__))
VARIANT = "wght600fill1"
URL = "https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web/{n}/materialsymbolsrounded/{n}_{v}_{px}px.svg"

names = [l.strip() for l in open(os.path.join(HERE, "names.txt")) if l.strip() and not l.startswith("#")]

def fetch(args):
    n, px = args
    try:
        svg = urllib.request.urlopen(URL.format(n=n, v=VARIANT, px=px), timeout=30).read().decode()
    except Exception as e:
        return n, px, None, str(e)
    d = " ".join(re.findall(r'\sd="([^"]+)"', svg))
    return n, px, d, None

out = {"20": {}, "40": {}}
bad = []
with ThreadPoolExecutor(16) as ex:
    for n, px, d, err in ex.map(fetch, [(n, px) for n in names for px in (20, 40)]):
        if d: out[str(px)][n] = d
        else: bad.append(f"{n} ({px}px): {err}")
if bad:
    print("could not fetch:\n  " + "\n  ".join(bad), file=sys.stderr)

with open(os.path.join(HERE, "..", "IconPaths.js"), "w") as f:
    f.write(".pragma library\n"
            "// GENERATED by Commons/icons/build.py from names.txt — do not edit.\n"
            "// Material Symbols Rounded (" + VARIANT + "), (c) Google, Apache License 2.0.\n"
            "// SVG path data in the symbols' own viewBox: 0 -960 960 960.\n")
    f.write("var small = " + json.dumps(out["20"], separators=(",", ":"), sort_keys=True) + ";\n")
    f.write("var large = " + json.dumps(out["40"], separators=(",", ":"), sort_keys=True) + ";\n")
print(f"{len(out['20'])} icons written")
sys.exit(1 if bad else 0)
