[General]
# GENERATED by orrery-theme — theme: {{ name }} ({{ mode }}). Do not edit.
# Synced to /usr/share/sddm/themes/orrery/theme.conf by orrery-sddm-sync.
background=background.png
blur=true
font=JetBrainsMono Nerd Font Propo
clock12h=true
preferSession=Hyprland
mode={{ mode }}
bg0={{ bg0 }}
bg2={{ bg2 }}
bg3={{ bg3 }}
bg4={{ bg4 }}
fg={{ fg }}
bright={{ accent_bright }}
mid={{ accent_mid }}
dim={{ accent_dim }}
